name: _test
on:
  workflow_dispatch:
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run api:load
      - run: npm install
      - run: CHANNELS_PATH=sites/tvtv.us/tvtv.us_us.channels.xml npm run queue:create -- --max-clusters=1 --days=2
      - run: NODE_OPTIONS=--insecure-http-parser npm run cluster:load -- --timeout=30000  --cluster-id=1